#!/usr/bin/python3
import os
import subprocess
import sys
import syslog
import socket
from cryptography.fernet import Fernet

# this is a pointer to the module object instance itself.
this = sys.modules[__name__]
this.enc_fernet_key_2 ="L4ceiS3xMkJ2AW0sPmZOUResvQARer4="
this.kinit = "/usr/bin/kinit"
this.ipa = "/usr/bin/ipa"
this.awk = "/usr/bin/awk"
this.gpg = "/usr/bin/gpg"
this.gpg_home = '/etc/salt/gpgkeys'
this.pillar_service_account = "/etc/salt/ipa/service_account"
this.pillar_service_password = "/etc/salt/ipa/service_password"
this.pillar_decryption_key = "/etc/salt/ipa/decryption_key"

def get_gpg_key():
    server_address = ('localhost', 8394)
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
        client_socket.connect(server_address)
        dec_info = client_socket.recv(1024).decode('utf-8')
        enc_fernet_key_1, gpg_enc_keyword = dec_info.split(",")
        enc_fernet_key = enc_fernet_key_1 + this.enc_fernet_key_2
        f = Fernet(enc_fernet_key.encode('utf-8'))
        decrypted_gpg_key = f.decrypt(gpg_enc_keyword.encode('utf-8'))
        return decrypted_gpg_key.decode()

def pillars():
    gpg_key = get_gpg_key()
    dec_service_account = subprocess.run(
        f"{this.gpg} --pinentry-mode=loopback --passphrase '{gpg_key}' --quiet --homedir '{this.gpg_home}' --decrypt {this.pillar_service_account}",
        shell=True, capture_output=True, text=True).stdout.strip()

    dec_service_password = subprocess.run(
        f"{this.gpg} --pinentry-mode=loopback --passphrase '{gpg_key}' --quiet --homedir '{this.gpg_home}' --decrypt {this.pillar_service_password}",
        shell=True, capture_output=True, text=True).stdout.strip()

    dec_decryption_key = subprocess.run(
        f"{this.gpg} --pinentry-mode=loopback --passphrase '{gpg_key}' --quiet --homedir '{this.gpg_home}' --decrypt {this.pillar_decryption_key}",
        shell=True, capture_output=True, text=True).stdout.strip()

    if not dec_service_account or not dec_service_password or not dec_decryption_key:
        syslog.syslog(syslog.LOG_INFO, "SALT-STACK -ERROR-(ipa vault module) invalid GPG key-ID, wrong password, or something else related to GPG")
        return "Invalid GPG key-ID, wrong password, or something else related to GPG"
    else:
        return dec_service_account, dec_service_password, dec_decryption_key

def aut():
    dec_service_account, dec_service_password, dec_decryption_key = pillars()
    return_code = subprocess.run(
        f"echo -n '{dec_service_password}' | {this.kinit} {dec_service_account}",
        shell=True, capture_output=True).returncode
    return return_code, dec_service_account, dec_service_password, dec_decryption_key

def retrieve_shared(vault_name):
    vault_requested = vault_name
    return_code, dec_service_account, dec_service_password, dec_decryption_key = aut()
    if return_code != 0:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK -ERROR-(ipa vault module) tried to decrypt {vault_requested} from freeipa vault but Kerberos credentials are invalid")
        return "Invalid Kerberos credentials or user locked"

    vault_retrieved = subprocess.run(
        f"{this.ipa} vault-retrieve {vault_name} --shared --password '{dec_decryption_key}' | grep Data | {this.awk} -F': ' '{{print $2}}' | base64 -d | xargs",
        shell=True, capture_output=True, text=True).stdout.strip()

    if not vault_retrieved:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK -NOT-FOUND-(ipa vault module) request {vault_requested} but is not present in freeipa vault, try with shared")
        return "not-found"
    else:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK (ipa vault module) requested and decrypted {vault_requested} from freeipa vault")
        return vault_retrieved

def retrieve(vault_name):
    vault_requested = vault_name
    return_code, dec_service_account, dec_service_password, dec_decryption_key = aut()
    if return_code != 0:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK -ERROR-(ipa vault module) tried to decrypt {vault_requested} from freeipa vault but Kerberos credentials are invalid")
        return "Invalid Kerberos credentials or user locked"

    vault_retrieved = subprocess.run(
        f"{this.ipa} vault-retrieve {vault_name} --password '{dec_decryption_key}' | grep Data | {this.awk} -F': ' '{{print $2}}' | base64 -d | xargs",
        shell=True, capture_output=True, text=True).stdout.strip()

    if not vault_retrieved:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK -NOT-FOUND-(ipa vault module) request {vault_requested} but is not present in freeipa vault, try without shared")
        return "not-found"
    else:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK (ipa vault module) requested and decrypted {vault_requested} from freeipa vault")
        return vault_retrieved

def store_shared(vault_name, secret, group_member, overwrite=False):
    vault_requested = vault_name
    return_code, dec_service_account, dec_service_password, dec_decryption_key = aut()
    if return_code != 0:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK -ERROR-(ipa vault module) tried to store {vault_name} in freeipa vault but Kerberos credentials are invalid")
        return "Invalid Kerberos credentials or user locked"

    secret = secret.strip()
    base64_secret = subprocess.run(
        f"echo -n '{secret}' | base64 -w 0",
        shell=True, capture_output=True, text=True).stdout.strip()

    return_code = subprocess.run(
        f"echo -n '{dec_decryption_key}' | {this.ipa} vault-add {vault_name} --desc {vault_name} --shared",
        shell=True, capture_output=True).returncode

    if return_code != 0 and not overwrite:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK -ERROR-(ipa vault module) tried to store {vault_name} in freeipa vault but vault already exists")
        return f"-ERROR- creating vault {vault_name} already exists"
    if return_code != 0 and overwrite:
        subprocess.run(f"{this.ipa} vault-del {vault_name} --shared", shell=True, capture_output=True)
        return_code = subprocess.run(
            f"echo -n '{dec_decryption_key}' | {this.ipa} vault-add {vault_name} --desc {vault_name} --shared",
            shell=True, capture_output=True).returncode

    if return_code != 0:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK -ERROR-(ipa vault module) tried to store {vault_name} in freeipa but something went wrong")
        return f"-ERROR- creating vault {vault_name}"

    return_code = subprocess.run(
        f"echo -n '{dec_decryption_key}' | {this.ipa} vault-archive {vault_name} --shared --data={base64_secret}",
        shell=True, capture_output=True).returncode

    if return_code != 0:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK -ERROR-(ipa vault module) tried to store {vault_name} in freeipa but something went wrong during archiving")
        return f"-ERROR- during archiving {vault_name}"

    if group_member != "none":
        return_code = subprocess.run(
            f"{this.ipa} vault-add-member --group {group_member} {vault_name} --shared",
            shell=True, capture_output=True).returncode

        if return_code != 0:
            syslog.syslog(syslog.LOG_INFO, f"SALT-STACK -ERROR-(ipa vault module) tried to store {vault_name} in freeipa but something went wrong adding group {group_member}")
            return f"-ERROR- adding group to {vault_name} is the group {group_member} exists?"

    validation_chksum = subprocess.run(
        f"{this.ipa} vault-retrieve {vault_name} --shared --password '{dec_decryption_key}' | grep Data | {this.awk} -F': ' '{{print $2}}' | xargs",
        shell=True, capture_output=True, text=True).stdout.strip()

    if validation_chksum == base64_secret:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK (ipa vault module) stored and encrypted {vault_name} in freeipa vault")
        return f"Vault {vault_name} stored successfully"
    else:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK -ERROR-(ipa vault module) tried to store {vault_name} in freeipa but something went wrong during validation")
        return f"Encryption/Decryption -ERROR- on {vault_name}"

def store(vault_name, secret, overwrite=False):
    vault_requested = vault_name
    return_code, dec_service_account, dec_service_password, dec_decryption_key = aut()
    if return_code != 0:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK -ERROR-(ipa vault module) tried to store {vault_name} in freeipa vault but Kerberos credentials are invalid")
        return "Invalid Kerberos credentials or user locked"

    secret = secret.strip()
    base64_secret = subprocess.run(
        f"echo -n '{secret}' | base64 -w 0",
        shell=True, capture_output=True, text=True).stdout.strip()

    return_code = subprocess.run(
        f"echo -n '{dec_decryption_key}' | {this.ipa} vault-add {vault_name} --desc {vault_name}",
        shell=True, capture_output=True).returncode

    if return_code != 0 and not overwrite:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK -ERROR-(ipa vault module) tried to store {vault_name} in freeipa vault but vault already exists")
        return f"-ERROR- creating vault {vault_name} already exists"
    if return_code != 0 and overwrite:
        subprocess.run(f"{this.ipa} vault-del {vault_name}", shell=True, capture_output=True)
        return_code = subprocess.run(
            f"echo -n '{dec_decryption_key}' | {this.ipa} vault-add {vault_name} --desc {vault_name}",
            shell=True, capture_output=True).returncode

    if return_code != 0:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK -ERROR-(ipa vault module) tried to store {vault_name} in freeipa but something went wrong")
        return f"-ERROR- creating vault {vault_name}"

    return_code = subprocess.run(
        f"echo -n '{dec_decryption_key}' | {this.ipa} vault-archive {vault_name} --data={base64_secret}",
        shell=True, capture_output=True).returncode

    if return_code != 0:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK -ERROR-(ipa vault module) tried to store {vault_name} in freeipa but something went wrong during archiving")
        return f"-ERROR- during archiving {vault_name}"

    validation_chksum = subprocess.run(
        f"{this.ipa} vault-retrieve {vault_name} --password '{dec_decryption_key}' | grep Data | {this.awk} -F': ' '{{print $2}}' | xargs",
        shell=True, capture_output=True, text=True).stdout.strip()

    if validation_chksum == base64_secret:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK (ipa vault module) stored and encrypted {vault_name} in freeipa vault")
        return f"Vault {vault_name} stored successfully"
    else:
        syslog.syslog(syslog.LOG_INFO, f"SALT-STACK -ERROR-(ipa vault module) tried to store {vault_name} in freeipa but something went wrong during validation")
        return f"Encryption/Decryption -ERROR- on {vault_name}"

